package com.example.knockitriderapp.Model

class MyOderModel(
    var uid: String,
    var city: String,
    var state: String,
    var pincode: String,
    var address: String,
    var latitude: Long,
    var longitude: Long,
    var productId: String,
    var qtyId: String,
    var productPrice: Int,
    var price: Int,
    var productCuttedPrice: Int,
    var qty: String,
    var qtyNo: Int,
    var productTitle: String,
    var timeStamp: Long,
    var coupon: String,
    var couponId: String,
    var delivery: String,
    var payment: String,
    var orderConfirmedDate: String,
    var shippedDate: String,
    var outForDeliveryDate: String,
    var deliveredDate: String,
    var id: String,
    var storeId: String,
    var riderId: String,
    var ratingProduct: String,
    var name: String,
    var number: String
) {

    constructor(): this(
        "",
        "",
        "",
        "",
        "",
        1,
        1,
        "",
        "",
        1,
        1,
        1,
        "",
        1,
        "",
        1,
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
    )
}